version: "3.7"

services:
  sui:
    container_name: sui
    restart: unless-stopped
    image: willfantom/sui:latest
    ports:
      - 8080:6999
    volumes:
      - ./configs:/sui
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - SUI_DEBUG=true
    labels:
      - sui.enabled=true
      - sui.protect=false
      - sui.icon=home
