version: "3.7"

services:
  sui:
    container_name: sui
    restart: unless-stopped
#    build: ./
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - 8080:6999
    volumes:
      - ./config:/sui
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    environment:
      - SUI_DEBUG=true
    labels:
      - sui.enabled=true
      - sui.icon=home

networks:
  default:
    name: web
    external: true
