name: CI

on:
  push:
    branches: 
      - latest
      - dev
      - v1
      - v2 
  pull_request:
    branches: 
      - dev

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build and push
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/sui
          #tags: ${GITHUB_REF##*/}
          tag_with_ref: true
          dockerfile: build/Dockerfile